sudo: required

language: node_js

node_js:
  - '8'
  - '9'

install:
  - cd ./src/cityhash && ./configure && sudo make install && pwd && cd ../.. && npm install

script: npm test
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
